[tool.mypy]
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true

pretty = true
color_output = true

[tool.autopep8]
max_line_length = 100
aggressive = 3

[tool.pytest.ini_options]
addopts = [
  "--strict-config"
]
required_plugins = [
  "pytest-pythonpath",
  "pytest-order"
]
testpaths = [
  "test"
]
python_paths = [
  "src"
]